version: '3.8'

services:
  tor:
    image: dperson/torproxy:latest
    container_name: tor
    restart: unless-stopped
    environment:
      - TOR_NewCircuitPeriod=30
      - TOR_MaxCircuitDirtiness=600
    # Note: you generally do NOT need to expose tor 9050 to the host for the app to work.
    # If you want to use tor from the host, uncomment the following line and ensure 9050 is free.
    # ports:
    #   - "9050:9050"
    networks:
      - tor_net

  web:
    build: .
    container_name: web-recon
    restart: unless-stopped
    environment:
      - TOR_SOCKS_URL=socks5://tor:9050
    ports:
      - "8000:8000"
    depends_on:
      - tor
    networks:
      - tor_net

networks:
  tor_net:
    driver: bridge
